Correction of the inability to translate some fields into other languages
Ctrlpanel-gg/panel pull request #866
Opened 2023-06-07 18:17 UTC by MrWeez

2023-06-08 10:24 UTC, AGuyNamedJens requested changes
You're forgetting some translations

2023-06-08 10:24 UTC, AGuyNamedJens commented on themes/default/views/servers/settings.blade.php
>                                <span class="text-success text-sm font-weight-bolder">@if($server->product->memory == 0)Unlimited @else {{$server->product->memory}}MB @endif</span>
If you're adding more translations i'd suggest translating the other words such as Unlimited as well :)

2023-06-08 10:24 UTC, AGuyNamedJens commented on themes/default/views/servers/settings.blade.php
>                                <span class="text-success text-sm font-weight-bolder">@if($server->product->disk == 0)Unlimited @else {{$server->product->disk}}MB @endif</span>
same as above

2023-06-08 10:24 UTC, AGuyNamedJens commented on themes/default/views/servers/settings.blade.php
>                                <span class="text-success text-sm font-weight-bolder">@if($server->product->cpu == 0)Unlimited @else {{$server->product->cpu}} % @endif</span>
same as the other 2

2023-06-08 12:01 UTC, MrWeez commented
> You're forgetting some translations

Thanks, I didn't notice right away. Fixed.

2023-06-08 12:12 UTC, MrWeez commented
> Incorrect syntax, I'll fix it now

Although no, that's right. I just checked the code on the panel from the main branch, forgetting that the changes were made in development

2023-06-08 12:20 UTC, AGuyNamedJens reviewed
Not sure if you've added the translations to their language files yet, otherwise looks good to me.

2023-06-08 12:27 UTC, MrWeez commented
> Not sure if you've added the translations to their language files yet, otherwise looks good to me.

I could upload the localization file of my panel (ru.json), but there are a lot of localized translation moments

2023-06-08 12:41 UTC, AGuyNamedJens commented
> > Not sure if you've added the translations to their language files yet, otherwise looks good to me.
> 
> I could upload the localization file of my panel (ru.json), but there are a lot of localized translation moments

https://github.com/Ctrlpanel-gg/panel/blob/development/lang just add the variables to these files, use google translate if you don't know all language variants for them.

2023-06-08 14:23 UTC, MrWeez commented
I am not responsible for the accuracy of the translation, but I seem to have added it everywhere)

2023-06-08 14:26 UTC, AGuyNamedJens approved these changes

2023-06-08 14:28 UTC, MrWeez commented
After the release of 0.10, I will most likely completely rework the Russian language, since now it looks very illiterate and at times it is not correct at all.

2023-06-08 14:33 UTC, AGuyNamedJens commented
> After the release of 0.10, I will most likely completely rework the Russian language, since now it looks very illiterate and at times it is not correct at all.

Sounds logical, as the current contributors don't speak Russian, lol.

2023-06-08 18:27 UTC, IceToast commented on lang/de.json
> +    "SERVER NAME": "SERVERNAMEN",
Why are those localizations full uppercase?

2023-06-08 19:20 UTC, MrWeez commented on lang/de.json
> +    "SERVER NAME": "SERVERNAMEN",
> Why are those localizations full uppercase?

https://github.com/Ctrlpanel-gg/panel/blob/5827a143747f911b75ae8f35d1d50083667a1d93/themes/default/views/servers/settings.blade.php#L36

https://github.com/Ctrlpanel-gg/panel/blob/5827a143747f911b75ae8f35d1d50083667a1d93/themes/default/views/servers/settings.blade.php#L57

https://github.com/Ctrlpanel-gg/panel/blob/5827a143747f911b75ae8f35d1d50083667a1d93/themes/default/views/servers/settings.blade.php#L78

2023-06-09 09:25 UTC, IceToast commented
Some conflicts need to be resolved, can be merged when they are

2023-06-09 09:35 UTC, closed without merging