mercadopago Integration
Ctrlpanel-gg/panel pull request #926
Opened 2024-01-25 21:47 UTC by drylian

Just as they told me, I converted Mercadopago to work in the development version of cpgg, I tested the code version (requests) in the main version of cpgg, as I was unable to make the development version work, but I can guarantee that all the api will be working. If there is a problem with the API, I will resolve it and give another pull, unlike the old one that used the SDK, I preferred to use Mercadopago's own (tested) API, since the SDK generated some warnings when used.

2024-02-28 11:19 UTC, 1day2die commented
This is awesome. Thanks!

2024-03-21 05:36 UTC, drylian commented
If you need anything or find an error, just let me know and I'll fix that part.😀

2024-04-12 11:23 UTC, IceToast commented on app/Extensions/PaymentGateways/MercadoPago/MercadoPagoExtension.php
> +    static function Checker(Request $request): void
Might want to follow the naming scheme already used in other payment gateways.

2024-04-26 09:02 UTC, IceToast requested changes

2024-04-26 09:02 UTC, IceToast commented on app/Extensions/PaymentGateways/MercadoPago/MercadoPagoSettings.php
> +    public ?string $access_token;
When you add the access_token as encrypted in the DB Migration it needs to be markes es encrypted in the Settings Class too.
https://github.com/spatie/laravel-settings?tab=readme-ov-file#encrypting-properties

2024-05-16 16:05 UTC, S0ly commented
I fixed the conflicts that was in the readme (dont forget to pull), the new readme does not show what system are used for payment because there are too mutch, whitout speaking of the addons that add even more :)

2024-05-22 20:46 UTC, MrWeez commented
Any news about the fixes?

2024-05-23 03:29 UTC, drylian commented
> @drylian Any news about the fixes?
I think it's correct now

2024-05-23 04:25 UTC, S0ly commented
@IceToast

2024-06-14 10:26 UTC, IceToast commented on app/Extensions/PaymentGateways/MercadoPago/MercadoPagoSettings.php
> +    public ?string $access_token;
This is still open*

2024-06-14 10:40 UTC, IceToast commented on app/Extensions/PaymentGateways/MercadoPago/MercadoPagoSettings.php
> +    public ?string $access_token;
@drylian

2024-07-24 14:24 UTC, IceToast approved these changes

2024-07-24 14:27 UTC, IceToast commented
@drylian  Sorry, can you resolve that conflict to make the permission this PR adds readable.

For reference: https://github.com/Ctrlpanel-gg/panel/pull/910

2024-07-24 17:48 UTC, drylian commented
> @drylian Sorry, can you resolve that conflict to make the permission this PR adds readable.
> 
> For reference: #910

this?

2024-07-24 17:54 UTC, MrWeez commented
> > @drylian Sorry, can you resolve that conflict to make the permission this PR adds readable.
> > For reference: #910
> 
> this?

You need to add Readable names for your permissions, as in #910

2024-07-24 18:06 UTC, drylian commented
> You need to add Readable names for your permissions, as in

![image](https://github.com/user-attachments/assets/cd41b77c-a4f5-42aa-9be8-64a9689b13ff)
I think that would be it, right? It's the only place that would need to change, the others still use arrays (views), and only this one had this change

2024-07-24 20:14 UTC, IceToast commented
> @MrWeez
> 
> ![image](https://private-user-images.githubusercontent.com/109999325/351824783-cd41b77c-a4f5-42aa-9be8-64a9689b13ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4NTIzMjAsIm5iZiI6MTcyMTg1MjAyMCwicGF0aCI6Ii8xMDk5OTkzMjUvMzUxODI0NzgzLWNkNDFiNzdjLWE0ZjUtNDJhYS05YmU4LTY0YTk2ODliMTNmZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNFQyMDEzNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMGIzNGY0NDQ1OTkwNTM0NzNkNWRkYjEwNzliYTYxZGUyZDViMmUxYzM4NzQ5OTE1MDk1ZGVkZTNiNWMyODIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.y5t-gpXXEw7McdchiP5I-UKAwYaaIly8rrt7GV73zu4) I think that would be it, right? It's the only place that would need to change, the others still use arrays (views), and only this one had this change

Looks goot to me

2024-07-24 20:14 UTC, merged

2024-08-31 11:06 UTC, andremods1 commented
Como adicionar?

2024-08-31 11:13 UTC, MrWeez commented
> Como adicionar?

This gateway is written for version 0.10, and it is incompatible with version 0.9.x

2024-08-31 12:30 UTC, MrWeez commented
> Então não dá pra ter o Gateway do mercado pago

I don't quite understand you. Please use English, thanks.

2024-08-31 12:36 UTC, drylian commented
> Então não dá pra ter o Gateway do mercado pago

O mercado pago ta disponível apenas para a versão development, eu fiz originalmente duas versões, uma para a 0.10 e a pra 0.9, porém não aceitaram ela por que não estão aceitando pull nela, caso queria a do 0.9 fale comigo no Discord:drylian

2024-08-31 12:51 UTC, andremods1 commented
Já te segui lá

2024-08-31 14:41 UTC, S0ly commented
speak English or nobody will help.

2024-08-31 15:00 UTC, andremods1 commented
Ok

2024-08-31 15:38 UTC, drylian commented
> speak English or nobody will help.

He wanted the Mercado Pago gateway for 0.9, but this code is for 0.10+, I made it for 0.9 too, but it's not on cpgg's Github because they weren't accepting pull requests in the "main" repo.

2024-11-04 20:03 UTC, 1day2die commented
@drylian any updates?

2024-11-04 20:12 UTC, drylian commented
> @drylian any updates?

He wanted the Mercado Pago gateway for 0.9, but this code is for 0.10+, I made it for 0.9 too, but it's not on cpgg's Github because they weren't accepting pull requests in the "main" repo.

2024-11-04 20:36 UTC, 1day2die commented
i saw that. 
if you can extract the code you can place it on the market. many people want it actually. if you want money for it or place it free is up to you. Otherwise i would jank your code and put it for free in the market until i implement it in v010

2024-11-04 20:42 UTC, drylian commented
> i saw that. if you can extract the code you can place it on the market. many people want it actually. if you want money for it or place it free is up to you. Otherwise i would jank your code and put it for free in the market until i implement it in v010

Honestly, if you want to do this, do it. I implemented the Mercado Pago code for people, and I really tried to put it in the official repository, but the people there didn't let me.
If you want to do it, at least tag me in the repository, so I can help