FEATURE: CryptoBot payments
Ctrlpanel-gg/panel pull request #940
Opened 2024-04-11 05:44 UTC by gru2007

I’m just adding new optional payment method

what is it? - https://help.crypt.bot/crypto-pay-api

2024-04-11 05:47 UTC, MrWeez commented
Hi! It looks very cool, but could you change the Russian localization to English?
Thank you for helping to improve cpgg ❤️

2024-04-11 05:47 UTC, gru2007 commented
Only one thing, for some reason money doesn’t add after sending event with payment. So I added this construction:
```php
try {
            $user->increment('credits', $payment->amount);
        } catch (Exception $exception) {
            throw $exception;
        }
```

I’m sure, that it is not right way to do that. I don’t know what happens in your code.

2024-04-11 05:48 UTC, gru2007 commented
> Hi! It looks very cool, but could you change the Russian localization to English? Thank you for helping to improve cpgg ❤️

Oh sorry, I have missed that. Couple minutes.

2024-04-11 08:24 UTC, 1day2die commented
awesome!

2024-04-11 08:25 UTC, 1day2die commented
> Only one thing, for some reason money doesn’t add after sending event with payment. So I added this construction:
> 
> ```
> try {
>             $user->increment('credits', $payment->amount);
>         } catch (Exception $exception) {
>             throw $exception;
>         }
> ```
> 
> I’m sure, that it is not right way to do that. I don’t know what happens in your code.

@IceToast  mind checking this?

2024-04-11 08:47 UTC, IceToast commented
So i see you've created a extension with all the necessary information. I will sketch out the payment workflow:

_User payment request -> URL fetching from extension -> Redirecting to payment URL -> ... -> Success redirection to success route of extension -> done_

_Gateway Webhook -> request to extension webhook route -> sets a payment as "paid" -> emits a user payment event -> payment listener updates user credits and possibly any new limits -> done_

The first thing i noticed is that you might want to validate that the webhook request actually wants to update a payment to the PAID status. In your PR it will set it to PAID under any circumstances? Maybe im missing something about the gateway.

For your problem: You should debug into [CryptoBotExtension.php:110](https://github.com/Ctrlpanel-gg/panel/pull/940/commits/69682665c5b587c673c10a341cfcbf839e377a42#diff-0712e40d30808236896ff485db3e8fd82a277dd9fe7119e10479d6a43ff0593bR110) to see whether the event really gets triggered and what da parameters are. If everything is processed correctly the event will be listened to in here: [Listeners/UserPayment.php](https://github.com/Ctrlpanel-gg/panel/blob/development/app/Listeners/UserPayment.php)

2024-04-11 11:02 UTC, gru2007 commented
@IceToast Thanks, I will come back with result soon.

2024-04-26 09:08 UTC, IceToast requested changes

2024-05-22 20:43 UTC, MrWeez commented
@gru2007 Is there any news about fixes?

2024-05-22 21:34 UTC, gru2007 commented
> @gru2007 Is there any news about fixes?

Excuse me for afk, I just haven’t enough time to solve that right now. I’ll do it in near future.

2024-05-22 21:35 UTC, MrWeez commented
> > @gru2007 Is there any news about fixes?
> 
> Excuse me for afk, I just haven’t enough time to solve that right now. I’ll do it in near future.

Ok, no problem

2024-07-24 14:37 UTC, S0ly commented
updated the branch @gru2007 any news ? :)

2024-07-25 12:00 UTC, MrWeez requested changes

2024-07-25 12:00 UTC, MrWeez commented on app/Extensions/PaymentGateways/CryptoBot/CryptoBotExtension.php
> + * Summary of PayPalExtension
Change or remove this comment

2024-07-25 12:00 UTC, MrWeez commented on app/Extensions/PaymentGateways/CryptoBot/CryptoBotExtension.php
> +                'description' => "Заказ #{$payment->id} - " . $shopProduct->name,
Replace **Заказ** with **Order**
```suggestion
                'description' => "Order #{$payment->id} - " . $shopProduct->name,
```

2024-07-25 12:00 UTC, MrWeez commented on app/Extensions/PaymentGateways/CryptoBot/CryptoBotExtension.php
> +                'paid_btn_url' => route('payment.CryptoBotSuccess').'?payment=YGqvOf4I'
I'm not quite sure if it's correct, can you double-check this part of the code? To be more precise, this -> `?payment=YGqvOf4I`

2024-07-25 12:00 UTC, MrWeez commented on app/Extensions/PaymentGateways/CryptoBot/CryptoBotExtension.php
> +        /***    Проверка подписи     ***/
Also translate this comment into English
```suggestion
        /***    Signature verification    ***/
```

2024-07-25 12:00 UTC, MrWeez commented on app/Extensions/PaymentGateways/CryptoBot/CryptoBotExtension.php
> +        /***                         ***/
Don't forget to delete unused lines of code (Even comments)
```suggestion
```

2024-07-25 12:00 UTC, MrWeez commented on app/Extensions/PaymentGateways/CryptoBot/CryptoBotExtension.php
> +        //update payment
Keep the style of writing the code, if you used a different type of comment formatting above, then save it to the end of the file
```suggestion
        /***    Update payment    ***/
```

2024-07-25 12:02 UTC, S0ly commented
damn good review

2024-07-25 12:04 UTC, MrWeez commented
> damn good review

I decided to double-check this PR so that there would be no problems in the future

2024-09-06 14:57 UTC, S0ly commented
any update ?

2024-09-24 03:26 UTC, S0ly commented
if there is no update soon this PR will be closed

2024-11-05 15:04 UTC, S0ly commented
closed for inactivity

2024-11-05 15:04 UTC, closed without merging