fix: LegacySettingsMigrations
Ctrlpanel-gg/panel pull request #941
Opened 2024-04-12 12:06 UTC by IceToast

This PR fixes the settingsmigration for all old settings as described here:
https://discord.com/channels/787829714483019826/851144461361872957/1203989679557312552

![image](https://github.com/Ctrlpanel-gg/panel/assets/54889359/1f78955e-95b8-43a8-a577-9062fb2ad2eb)

2024-04-18 17:00 UTC, Ferks-FK commented on app/Classes/LegacySettingsMigration.php
> +            case 'string':
Don't need a return for the `string` type?

2024-04-18 17:10 UTC, Ferks-FK requested changes
Just a few changes.

2024-04-19 16:55 UTC, IceToast commented on database/settings/2023_02_01_181334_create_pterodactyl_settings.php
> +        // $this->migrator->add('pterodactyl.admin_token', $table_exists ? $this->getOldValue('SETTINGS::SYSTEM:PTERODACTYL:TOKEN') : env('PTERODACTYL_TOKEN', ''));
True that!

2024-04-22 17:53 UTC, 1day2die commented on routes/web.php
> +        if ($serverSettings->creation_enabled) {
rest lgtm

2024-04-24 08:50 UTC, 1day2die commented
lgtm

2024-04-25 13:27 UTC, merged